FROM golang:1.14 AS build

ARG ORACLE_VERSION
ENV ORACLE_VERSION "${ORACLE_VERSION}"
ENV LD_LIBRARY_PATH "/usr/lib/oracle/${ORACLE_VERSION}/client64/lib"

RUN apt-get -qq update && apt-get install --no-install-recommends -qq libaio1 rpm libgcc1
COPY oci8.pc.template /usr/share/pkgconfig/oci8.pc
RUN sed -i "s/@ORACLE_VERSION@/$ORACLE_VERSION/g" /usr/share/pkgconfig/oci8.pc
COPY oracle*${ORACLE_VERSION}*.rpm /
RUN rpm -Uh --nodeps /oracle-instantclient*.x86_64.rpm && rm /*.rpm
RUN echo $LD_LIBRARY_PATH >> /etc/ld.so.conf.d/oracle.conf && ldconfig

WORKDIR /go/src/oracle-exporter
COPY . .
RUN go get -d -v

ARG VERSION
ENV VERSION ${VERSION:-0.1.0}

ENV PKG_CONFIG_PATH /go/src/oracle-exporter
ENV GOOS            linux

RUN go build -v -ldflags "-X main.Version=${VERSION} -s -w"

FROM frolvlad/alpine-glibc:glibc-2.29
LABEL authors="Seth Miller,Yannig Perré"
LABEL maintainer="Danijel Fischer <danijel@stojnic.com>"

ENV VERSION ${VERSION:-0.1.0}

RUN apk add libaio

COPY --from=build /usr/lib/oracle /usr/lib/oracle
COPY --from=build /go/src/oracle-exporter/oracle-exporter /oracle-exporter

ARG ORACLE_VERSION
ENV ORACLE_VERSION=${ORACLE_VERSION}
ENV LD_LIBRARY_PATH "/usr/lib/oracle/${ORACLE_VERSION}/client64/lib"
RUN ldconfig "$LD_LIBRARY_PATH"

RUN chmod 755 /oracle-exporter

ADD ./oracle.conf /etc/oracle-exporter/
EXPOSE 9161

ENTRYPOINT ["/oracle-exporter"]