FROM golang:1.14 AS build

ARG ORACLE_VERSION
ENV ORACLE_VERSION=${ORACLE_VERSION}
ENV LD_LIBRARY_PATH "/usr/lib/oracle/${ORACLE_VERSION}/client64/lib"

RUN apt-get -qq update && apt-get install --no-install-recommends -qq libaio1 rpm
COPY oci8.pc.template /usr/share/pkgconfig/oci8.pc
RUN sed -i "s/@ORACLE_VERSION@/$ORACLE_VERSION/g" /usr/share/pkgconfig/oci8.pc
COPY oracle*${ORACLE_VERSION}*.rpm /
RUN rpm -Uh --nodeps /oracle-instantclient*.x86_64.rpm && rm /*.rpm
RUN echo $LD_LIBRARY_PATH >> /etc/ld.so.conf.d/oracle.conf && ldconfig

WORKDIR /go/src/oracle-exporter
COPY . .
RUN go get -d -v

ARG VERSION
ENV VERSION ${VERSION:-0.1.0}

ENV PKG_CONFIG_PATH /go/src/oracle-exporter
ENV GOOS            linux

RUN go build -v -ldflags "-X main.Version=${VERSION} -s -w"


FROM oraclelinux:7-slim

ARG ORACLE_VERSION
ENV ORACLE_VERSION=${ORACLE_VERSION}
RUN yum -y install oracle-release-el7 && \
    yum -y --setopt=tsflags=nodocs update && \
    # yum list oracle-instantclient* && \
    yum -y --setopt=tsflags=nodocs install oracle-instantclient${ORACLE_VERSION}-basic.x86_64  && \
    yum clean all

COPY --from=build /go/src/oracle-exporter/oracle-exporter /oracle-exporter

RUN chmod 755 /oracle-exporter && \
    groupadd www-data && useradd -g www-data www-data
USER www-data
ENV LD_LIBRARY_PATH "/usr/lib/oracle/${ORACLE_VERSION}/client64/lib"

EXPOSE 9161

COPY ./oracle.conf.example /etc/oracle-exporter/oracle.conf
ENTRYPOINT ["/app/oracle-exporter", "-configfile", "/etc/oracle-exporter/oracle.conf"]